# Rerun after changes: conda env update --file environment.yml --prune

name: prob_tcn_for_LED
channels:
  - conda-forge
  - defaults
dependencies:
  - pip>=23
  - python=3.11
  - numpy>=1.26,<2
  - matplotlib>=3.8
  - pandas>=2.0
  - scikit-learn
  - zarr
  - pyyaml
  - tqdm
  - scipy
  - wandb
  - seaborn
  - pyserial
  - ipykernel
  - pip:
      - torch==2.4.1
      - torchaudio==2.4.1
      - pyvisa
      - pyflux @ git+https://github.com/UW-Photonics-Lab/PyFlux.git@prototype/v1